//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Problems.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Problems.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID,City,Cuisine,Rating
        ///1,Mumbai,Dairy,99
        ///2,Jakarta,Meat,55
        ///3,Delhi,Vegan,69
        ///4,Paris,Vegan,65
        ///5,Seoul,Meat,21
        ///6,Moscow,Meat,54
        ///7,Mumbai,Meat,88
        ///8,Tokyo,Meat,72
        ///9,Manila,Meat,49
        ///10,Beijing,Vegan,80
        ///11,Shanghai,Meat,78
        ///12,Jakarta,Vegan,74
        ///13,Seoul,Vegan,87
        ///14,Moscow,Vegan,75
        ///15,Mumbai,Vegan,70
        ///16,Tokyo,Vegan,76
        ///17,Manila,Vegan,84
        ///18,Shanghai,Vegan,53
        ///19,Jakarta,Dairy,89
        ///20,Delhi,Dairy,64
        ///21,Paris,Dairy,74
        ///22,Seoul,Dairy,91
        ///23,Moscow,Dairy,74
        ///24,Mumbai,Dairy,64
        ///25,Tokyo,Dairy,57
        ///26,Man [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string restaurant_ratings {
            get {
                return ResourceManager.GetString("restaurant-ratings", resourceCulture);
            }
        }
    }
}
